/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */
import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string>;

export interface Emojis {
  created_at: Generated<Timestamp>;
  emoji: string;
  id: Generated<Int8>;
  lang: string;
  post_id: Int8 | null;
  profile_id: Int8 | null;
}

export interface Posts {
  cid: string;
  created_at: Generated<Timestamp>;
  did: string;
  has_emojis: Generated<boolean>;
  id: Generated<Int8>;
  langs: Generated<string[]>;
  rkey: string;
  text: string | null;
}

export interface Profiles {
  cid: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  did: string;
  display_name: string | null;
  id: Generated<Int8>;
  rkey: string;
}

export interface DB {
  emojis: Emojis;
  posts: Posts;
  profiles: Profiles;
}
